### ISSUE TITLE
CFCC Rate Limiting

### ISSUE THREAD

**Issue by eaglerainbow** [promregator/promregator#171]
## Environment

Version: 0.7.4
High number of applications to scrape.

for updates see also #170 

## Summary / Problem Statement
We need to rate limiting on CFCC metadata calls. 

## Observed Behavior
Error message `503:`

## Expected Behavior
Either we (Promregator) or our library (cf-java-client) has a throttle.

**Comment by eaglerainbow** [comment]
Side note: Just found this on [CF rate limiting](https://docs.cloudfoundry.org/running/rate-limit-cloud-controller-api.html).

**Comment by eaglerainbow** [comment]
Interesting side note:

The error message reported is `503: the server (api.mycompany.org) has reached the connection limit.`.
https://docs.cloudfoundry.org/running/rate-limit-cloud-controller-api.html however mentions that the message returned by CFCC on overload situations is: `429: Too Many Requests`.

==> This does not match.

Hypothesis: Not the CFCC is rate limiting but the load balancer infront does not have enough capacity and hence blocks traffic? 

If this assumption held true, then it would not make much of a difference: The sender has to throttle. However, it would show that it *may* be irrelevant to determine capacity for throttling based on `X-RateLimit-*` HTTP headers.

**Comment by eaglerainbow** [comment]
See also branch `metadataRateLimiter`.
Still to be done:
* unit testing
* double maintenance into `simplifiedProm`

**Comment by eaglerainbow** [comment]
mmmh. I am getting second thoughts about the implementation here: 
Right now rate limiting is located *above* the ReactiveCFPaginatedRequestFetcher, which means that one "permit" still could be resolved into multiple CF requests (e.g. if one set of data contains multiple pages). 
However, as long as the cardinality of different cf entities isn't getting high, then this should not matter too much (e.g. only high number of objects at org level  doesn't harm)

**Comment by checketts** [comment]
I would like to see the the discovery recover and instead of just being slowed by the rate limit, return a result for discovery, along with a flag indicating that only a partial result had been achieved (so it can report it in the logs and/or wait and retry again if needed).

Then on a subsequent discovery, it could discovery more (since some of the requests had been cached). Eventually the system would have a complete picture, and we could rate limit how long that picture takes to come together.

**Comment by eaglerainbow** [comment]
Your approach would mean that you need to implement a logic for `curl`ing the `/discovery` endpoint until it is complete. Though I see the benefit that your partial result could already be used, what would be the trigger for stopping to call it?
And what shall Promregator do if the quota of requests is exceeded, while we are during a scraping endpoint call (remember, we aren't yet there with promLite where we don't need discovery during scraping 😬 )? Shall we stop there, too?

**Comment by checketts** [comment]
Sorry, I meant that the internal discovery would recover and deliver a partial result to the `/discovery` endpoint.

For example currently, if there are 300 applications, but due to rate limiting/timeouts with the CFCC only 200 are fully discovered, the `/discovery` endpoint will return 200 (and maybe an http status code 206 - Partial Content) Then on the next periodic `/discovery` call it would hopefully fetch the remaining 100 entries, due to having cached the network calls for the other 200 already and not needing to hit the CFCC for those again. 

I also am considering basing it on total time taken. So if there is plenty of capacity, but all the network calls are just taking a long time, we would return all that we had collected so far in 15 seconds (configurable). This way we are in control of how large our request waves are, and not only dependent on the CFCC dying for us to ratelimit.

**Comment by eaglerainbow** [comment]
> Sorry, I meant that the internal discovery would recover and deliver a partial result to the /discovery endpoint.

That's exactly what I was assuming before.

With your approach you are making the `/discovery` endpoint unreliable in that sense that you must check the HTTP status code / the content whether you have to retrigger the process again. 
I try to picture the situation in my own CF case: I have a small shell script, which is triggered roughly every 5 minutes. I don't want to run it more often than this. However, I want to have a consistent response, namely I want to have all my apps. As it is a background process (scheduled via cron), I don't care whether it takes 10 seconds or 3 minutes. However, if Promregator stopped processing early and provided a partial result too early, the script needs to check that it is partial and what should the script do in case of incompleteness...? I would retrigger the same process immediately again to make sure that I get the full result. Why will I do it? Because I don't know "which part is missing" - so the data could be crap, or be missing cases, which I had used for scraping before (hence removing valid targets). 
The point is that I don't want to wait another five minutes, but I want to get the consistent&complete data now. 
This brings me to the next problem: Rate limiting on the CFCC will still be in place, if I trigger immediately again. So, I should "wait a little" before I give it a next try. Okay, but what is the value? The shell script has no easy way to find out whether "bad times" are over...

My other approach is going a different direction: By setting a rate which can be customized, the administrator can tweak the value low enough such that (hopefully) the platform's rate limit never is exceeded. By that response content and call latency of `/discovery` stays equally predictable - but there is no need to repeat the call. 

What are the benefits for your approach which you see, but I am missing right now?

**Comment by jim-mclean** [comment]
Just chiming in with an opinion from a end user's perspective...

- The only time we would have an incomplete set of data is at startup, later refreshes will have at worst stale data.  IMO this is acceptable and I can wait another 5 mins after startup to get the complete dataset.
- In general, I'd rather not have to tune promregator to get it to work.  Being tolerant of slow responses by design would be much preferred.

**Comment by checketts** [comment]
I'm mainly trying to avoid the case when all the discovery wouldn't be completeable in the time between discovery. For instance if you are checking every 5 minute and it would take 10 minutes, then dicoveries are piling up (hopefully the cache would balance it eventually)

> With your approach you are making the `/discovery` endpoint unreliable in that sense that you must check the HTTP status code / the content whether you have to retrigger the process again.

My goal wouldn't be to have the enduser know to have to retry, but include the `206` status code so they could be aware of it. Retrying is much simpler within the Reactor context itself. So more likely we could include config that the internal discovery could use to determine if it should keep retrying or just return the data it has gathered so far.

Your throttling work is a good way to give someone like #170 options. My goal is to make it so Promregator won't need to be fine tuned (similar to how @jim-mclean pointed out).

**Comment by eaglerainbow** [comment]
>  later refreshes will have at worst stale data.

This only holds true, if you are using Caffeine Cache.
The classic cache may evict items and may leave a "hole in your cache" even later. 
As your initial set of metadata values have been created almost at the same point in time and the TTL in the cache is always the same for each entry, you will also lose all the cache information at almost the same point in time. 

> In general, I'd rather not have to tune promregator to get it to work. Being tolerant of rate limits/fault/slow responses by design would be much preferred.

I echo this. The problem with the original use case (from #170) to my mind is that we cannot properly predict - and hence auto-throttle - when it is "too much for the CFCC" (more on why this is a problem in one of my next posts here in this issue).

**Comment by eaglerainbow** [comment]
> My goal wouldn't be to have the enduser know to have to retry, but include the 206 status code so they could be aware of it. 

I see your point. However, what is with this:

@tlkamp has a point in her statement 

> If I were being rate-limited,...

at https://github.com/promregator/promregator/issues/170#issuecomment-596563518 , which mainly says that she is not hitting any rate limit imposed by the CFCC, but she's even killing it with all the requests Promregator generates. 
Seen from positive point of view, we have proof that we have built such an efficient "request generator" by using netty client that we are able to flood the CFCC even without us starting to sweat. Instead, the other machine just is able to error out. We are even so great that she isn't daring to "step on the gas" even more, as she fears to crash the CFCC's machine (that there is no protection in front of the CFCC is another thing...).

Here's my point on that: If we go for "partial discovery response", we still will have to hold back requests. If we don't, we will run into the situation that we trigger the flood of requests, half of them will come back with an error - and the CFCC will crash. Then we could deliver back (let's say) 10% of the resolved targets (if we were fast enough and came down to application level before the CFCC crashed). On the next round, we get another 10%, but with another CFCC crash. We may continue like this - and eventually will succeed. But this does not sound like a good idea to me. 
To that end I don't see any other possibility to prevent the CFCC from crashing other than not creating too many requests from the client side... in that sense we must become "better citizens". 

The bad thing is that, as of today, we can only make this a configuration parameter, which requires to be adjusted manually. However, at least by default we can disable rate limiting, so "normal users" won't be affected by this too much. 
To my mind we can only improve the configuration situation (and derive the throttling parameter automatically), if we would get notified by the cf-java-client library in one way or the other indicating to us that we were too fast (or the library throttles by itself). As long as the library's interface does not give us such an option, we must be preventive and don't start asking too much in first place.

@checketts Though I have the impression that my opinion is currently quite fixed, I'd still like to listen to you how you want to handle the situation of flooding the CFCC with partial discovery responses. Perhaps I am missing a point here.

**Comment by eaglerainbow** [comment]
@checketts  Oh damn... I just saw your #173 . Are you aware of https://github.com/promregator/promregator/tree/metadataRateLimiter ?

**Comment by checketts** [comment]
@eaglerainbow Yes I was aware of that branch which is taking a throttling approach. I wanted to spike and see how partial discovery/retrying could work.

By default right now in fact we are retrying 2 times in the `ReactiveCFPaginatedRequestFetcher`, we should remove that so we don't flood the CFCC (or at least add a backoff period).

So #173 changes it to a retry at the top instead of the lower level.

**Comment by eaglerainbow** [comment]
> By default right now in fact we are retrying 2 times in the ReactiveCFPaginatedRequestFetcher, we should remove that so we don't flood the CFCC (or at least add a backoff period).

I agree to idea of backing off. Such a behavior could @tlkamp the ability to recover, even if Promregator briefly had overshot the bearable rate limit.
I only have some issues with finding appropriate min/max backoff values here. I think they need to be configurable, but I don't really have a clue what good default values would be. Your 1s and 10s look rather arbitrary to me. And waiting up to 10 seconds is hell lot when we want to get 3000 targets within 60s or so.

**Comment by eaglerainbow** [comment]
I think I can express the major difference of our two approaches:
* You want to put a quota on `/discovery` in terms of "number of metadata requests`.
* I want to have limiting in place (so, number of metadata requests are infinite to me, but I want to throttle).

**Comment by eaglerainbow** [comment]
> For instance if you are checking every 5 minute and it would take 10 minutes, then dicoveries are piling up (hopefully the cache would balance it eventually)

Yes, piling up discovery requests isn't nice. 
I don't think that we will run into big issues with them, though: Thanks to Ben's `AsyncLoadingCache`, additional requests to the same key would just be blocked in case that the cache is empty. If the cache is full, but requires refreshing, still the old value is returned to the consumer. 
Things only could become hairy, if the expiry timing of the AsyncLoadingCache for orgs would be shorter than those of spaces (for instance). But I have never seen anyone doing such a mess (it's TTL inversion of a hierarchical cache structure 😲 ).

**Comment by checketts** [comment]
I've been playing with the `metadataRateLimiter` branch and I have 2 concerns:

# ReactiveCFPaginatedRequestFetcher usage

In prom-lite I refactored this class out completely in favor of using a `compose` operator to combine the 'generic' logic and also to leverage the cf-java-client's built in paginator.  I haven't pushed it upstream since it ends up eliminating the `ReactiveTimer` and I wanted to find a better solution for the metrics, I just wanted to point that out, since these changes lean on it even more

# Failing to ever get a result

I set the ratelimit to something extremely small (1), and with my current setup since I'm making about 45 requests. I would expect the result to comeback in 45 seconds or so. However, I'm not able to get any result. I'm doing further research to find out. The current error I'm seeing is:

```
2020-03-10 09:35:34.610  WARN 61971 --- [     parallel-2] o.c.p.scanner.ReactiveTargetResolver     : Error on retrieving list of applications in org 'MyOrg' and space 'myapp-dev'

java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:288) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:273) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:390) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

I'm guessing that was a timeout due to waiting for the `aqcuire`, but I'm confused as to why subsequent calls won't succeed, since I would think some of the data is being cached and eventually we should have it all cached and it would begin succeeding.

**Comment by checketts** [comment]
# Update regarding very low ratelimiting:

I was able to make it work with the extremely low rate limit. We just need to change the `timeout` as seen here: https://github.com/checketts/promregator/commit/b151afd14dc4ae4fbbcdcc7a8d04d3c6a3e538f0  

I wasn't able to push to the branch itself since I don't have permissions.

**Comment by eaglerainbow** [comment]
> ReactiveCFPaginatedRequestFetcher usage

I get what you mean and I understand why you don't like the current approach. I also had a bad feeling about there, but I consider helping to fix Traci's issue has more priority than our refactoring.

I am not religious about the `ReactiveTimer`. For me this is just a tool. However, what is important to me is that we have some sort of proper information on what is the latency of the CFCC we observe. As we see in #170, they might be totally undersized --- and users of Promregator will start complaining here in the issues why they see so many errors reported in the logs. I want to have a "weapon" here for this kind of discussion when providing support...

> very low ratelimiting

I was aware of that situation (because I also tested rate limiting with value 1 locally 😁) - and also had some thoughts about moving the timeouts. However, they were not mature enough to include them into the PR.
I'll have a look at your suggestion asap (sorry - again already very late here 😢 ), but moving the timeout from the overall request level to the page level was also my preferred approach so far.

**Comment by checketts** [comment]
Thanks for the feedback. Good that we are more or less aligned. With my suggested change (and also changing the ratelimit default to something other than 0, I think we have a via release candidate for Traci.

I definitely don't want to hold up the release due to future ideas on refactoring.

**Comment by eaglerainbow** [comment]
> and also changing the ratelimit default to something other than 0

Did you send a commit for that already? What value would you suggest as default value, if not disabling rate limiting?
My idea here right now is: Compatibility. If we defined a value, which had the semantics of not disabling it, we would be IMHO incompatible.

**Comment by eaglerainbow** [comment]
solution is contained in 0.8.0-rc1
However, there is still several things to be done before we can close this issue here (see in PR #174).
