### ISSUE TITLE
 Async retrieval of retrieveAllApplicationIdsInSpace with key raised a reactor error

### ISSUE THREAD

**Issue by Niranchana-dev** [promregator/promregator#224]
Trying to Scrape logs from CloudFoundry Environment, but getting the Exception org.cloudfoundry.promregator.endpoint.ScrapingException: Unable to determine any instance to scrape

LOGS  in the Application :

Async retrieval of retrieveAllApplicationIdsInSpace with key XXXXX|YYYYYY raised a reactor error

reactor.core.Exceptions$RetryExhaustedException: Retries exhausted: 2/2
	at reactor.core.Exceptions.retryExhausted(Exceptions.java:290) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.util.retry.RetryBackoffSpec.lambda$static$0(RetryBackoffSpec.java:67) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.util.retry.RetryBackoffSpec.lambda$generateCompanion$4(RetryBackoffSpec.java:557) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:376) [reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251) [reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.16.jar:3.4.16]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.16.jar:3.4.16]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[na:1.8.0_291]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_291]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_291]
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 2500ms in 'Mono.checkpoint ⇢ at org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.list(ReactorApplicationsV2.java:155)' (and no fallback has been configured)
	... 14 common frames omitted

2022-04-11 16:56:13.905 ERROR 19656 --- [     parallel-3] reactor.core.publisher.Operators         : Operator called default onErrorDropped

Pls Help in identifying the issue

**Comment by checketts** [comment]
Can you add any details? What version of Promregator are you using? Was it working previously?

**Comment by Niranchana-dev** [comment]
The Promregator version - v0.10.2 , We are trying to connect CF API version: 3.59.0. No this is the first time we are setting up the Promregator Application

**Comment by checketts** [comment]
Please try version 0.10.1

**Comment by Niranchana-dev** [comment]
Tried the version 0.10.1, getting the same issue. 

The test Application(A) deployed in Cloud foundry shows the the log metrics for  path ' /actuator/prometheus' but the Test Application (A) logs metrics is not scrapped by promregator Application. Added the required configuration in Application.yml of Promregator. 
Pls help on this. Getting the same issue.


 [nio-8080-exec-1] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Using 'text/plain;version=0.0.4;charset=utf-8;q=0.8', given [text/html, application/xhtml+xml, image/avif, image/webp, image/apng, application/xml;q=0.9, application/signed-exchange;v=b3;q=0.9, */*;q=0.8] and supported [text/plain;version=0.0.4;charset=utf-8]
 [nio-8080-exec-1] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Writing ["org.cloudfoundry.promregator.endpoint.ScrapingException: Unable to determine any instance to scrape"]
 [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed 503 SERVICE_UNAVAILABLE
 [     parallel-5] .c.p.c.ReactiveCFPaginatedRequestFetcher : Async retrieval of retrieveAllApplicationIdsInSpace with key XXXXXXXXXXXXX|YYYYYYYYYYYYYYYY raised a reactor error

**Comment by checketts** [comment]
This looks like you haven't configured Promregator to scrape any orgs/spaces. Or it is configured to scrape but isn't matching any values. The `0.10.1` logs look better than the previous one. Stick with that version.

Can you share any of your `targets` config?

**Comment by checketts** [comment]
And the username/password has access to the org/space?

**Comment by eaglerainbow** [comment]
@checketts  is right: Right now, Promregator can't find any instance which it could scrape.

Which endpoint are you calling at Promregator?

Could you send us the log output when hitting promregator's endpoint `/discovery`?

PS: The log statement

``` 
Async retrieval of retrieveAllApplicationIdsInSpace with key XXXXXXXXXXXXX|YYYYYYYYYYYYYYYY raised a reactor error
``` 
gives a first indication that the space might be visible to the user, but there is no application (with the specified name) in the space - or there is some authorization missing.

**Comment by Niranchana-dev** [comment]
The username/password has access to the org/space. 

We tried a standalone application connecting to Cloud Foundry via **CloudFoundryOperation client from SpringbootApplication**, we are able to **retrieve the all application details** which are deployed in CloudFoundry, so there is access for the username and password provided.

Async retrieval of retrieveAllApplicationIdsInSpace with key XXXXXXXXXXXXX|YYYYYYYYYYYYYYYY raised a reactor error --> Here the XXX and YYY denotes the KeyIds for the applications. We tried increasing the timeout period, still facing the same issue.

We are trying to run the promregator in local as well as deployed, Getting the same as below.
![Capture](https://user-images.githubusercontent.com/67929583/162898837-2e0f6ca0-8e06-4adc-91aa-4b2231c99596.PNG)

**Comment by checketts** [comment]
Thanks for testing that and eliminating the access as the root cause. Try simplifying the target, perhaps that is the problem. 


```
  targets:
    - orgName: XXXXXXXX
      path: '/actuator/prometheus
```

**Comment by Niranchana-dev** [comment]
` targets:
    - orgName: XXXXXXXX
      path: '/actuator/prometheus`

Tried specifying only the orgName and path in the targets, It is picking the Applications deployed in Space **INT06** , we did not specify the space in Targets. it picks random space, but we want to run in specific space.

 When tried mentioning the Specific Space along with org and path, we are getting the same error
 ```
[nio-8080-exec-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to org.cloudfoundry.promregator.endpoint.MetricsEndpoint#getMetrics()
 [     parallel-6] .c.p.c.ReactiveCFPaginatedRequestFetcher : Async retrieval of retrieveAllApplicationIdsInSpace with key XXXXXXXXXXX|YYYYYYYYYYYY raised a reactor error
```

**Comment by checketts** [comment]
Sorry I had overlooked the original error.

```
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 2500ms
```

Please set the following property, which will give you 10 seconds instead of 2.5 seconds:
```
cf.request.timeout.appInSpace: 10000
```

There are other timeouts that can be tweaked as well.

**Comment by eaglerainbow** [comment]
@checketts good point

@Niranchana-dev : How many applications (and instances of applications) are running in that particular space you want to scrape?
If you enter the space using the command line tool `cf` and enter `cf apps`, how long does it take until the response comes back? (If you are under Linux, try using `time cf apps` to get a brief measurement)

**Comment by eaglerainbow** [comment]
@Niranchana-dev 
> We tried increasing the timeout period, still facing the same issue.

Which timeouts did you change? Which values did you try out?

@checketts Please also mind that statement as well.

**Comment by eaglerainbow** [comment]
Visiting this issue here again, there is one more thing which comes to my mind when you write

> When tried mentioning the Specific Space along with org and path, we are getting the same error

Could it be that we are running here (again) into some upper-case/lower-case issue? We've had this some time ago (and I thought I would have fixed it).
Could you check that you are not mixing up case of letters here?

**Comment by eaglerainbow** [comment]
My best guess here right now is https://github.com/promregator/promregator/issues/224#issuecomment-1098303818: If the system tells us that it couldn't retrieve the metadata of all apps in a space within 2.5 seconds, then we have to increase the timer.

Food for the brain: Could also be a rate-limit issue (see also https://github.com/promregator/promregator/blob/3796954ab51bd0f9297303ca308721534bdc9951/docs/config.md#option-cfrequestratelimit-optional ).
