### ISSUE TITLE
NPE due to missing `# HELP` statement in the scraped metrics

### ISSUE THREAD

**Issue by jensbaitingerbosch** [promregator/promregator#73]
## Environment
Promregator 0.5.0-beta2
Prometheus Pushgateway 0.4.0

## Summary / Problem Statement
When one of the apps provides metrics without a `# HELP` statement, An NPE is thrown. E.g. the Prometheus Pushgateway 0.4.0 

Example: (removed sensitive data)
```
# HELP messages_published_seconds_max Time to publish a message
# TYPE messages_published_seconds_max gauge
messages_published_seconds_max{messageType="xxx"} 0
messages_published_seconds_max{messageType="zzz"} 0.014759974
messages_published_seconds_max{messageType="yyy"} 0.006648671
# TYPE messages_received_errors_total counter
messages_received_errors_total{errorType="invalidMessageType"} 0
messages_received_errors_total{errorType="missingId"} 0
```

## Observed Behavior
An NPE is thrown 

```
 2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at io.prometheus.client.exporter.common.TextFormat.writeEscapedHelp(TextFormat.java:55) ~[simpleclient_common-0.1.0.jar!/:na]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:26) ~[simpleclient_common-0.1.0.jar!/:na]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.promregator.rewrite.MergableMetricFamilySamples.toType004String(MergableMetricFamilySamples.java:78) ~[classes/:na]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.promregator.endpoint.AbstractMetricsEndpoint.handleRequest(AbstractMetricsEndpoint.java:136) ~[classes/:na]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.promregator.endpoint.MetricsEndpoint.getMetrics(MetricsEndpoint.java:39) ~[classes/:na]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158) ~[spring-security-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) ~[spring-security-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) ~[spring-security-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
   2018-09-13T08:47:08.18+0200 [APP/PROC/WEB/0] OUT     at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
[...]
```

## Expected Behavior
*describe what behavior you would have expected (instead)*
The fact that the there is no HELP is ignored (e.g. an empty HELP will be rendered)

**Comment by eaglerainbow** [comment]
I have seen your ticket; will have a look at it most likely at the weekend...

**Comment by jensbaitingerbosch** [comment]
I debugged a bit... `TextFormat004Parser` in line 171 takes the help string (which is not present and therefore `null`) and puts that in the `MetricFamilySamples`. Later when merged metrics are rendered, this results in the NPE.

**Comment by eaglerainbow** [comment]
Yep, you are right. But https://prometheus.io/docs/instrumenting/exposition_formats/ explicitly mentions that

> All lines for a given metric must be provided as one single group, with the optional HELP and TYPE lines first (in no particular order). 

So, it tends to be more a bug (missing support of a feature).

However, the client library has a check implemented under https://github.com/prometheus/client_java/blob/1950cff385518eae45651df47547f80547d72c1a/simpleclient/src/main/java/io/prometheus/client/SimpleCollector.java#L165, which prevents metrics not having any help. So, that is quite strange: There are prometheus metrics out there, where the `HELP` is optional, but all Java Clients (using prometheus/simpleclient) *must* will have to generate a `HELP`. On the other hand, there is no documentation on why this is required or that this is intentional (e.g.  http://prometheus.github.io/client_java/io/prometheus/client/SimpleCollector.html) - besides the exception raised.

I am currently asking myself what Promregator should do best:
* Create a dummy/fake `HELP` line to just satisfy `simpleclient`.
* Pushing into the direction to make `TextFormat` (of `simpleclient`) more flexible - even with the risk that Promregator must have its own copy.  

In general, it's the aim of Promregator to forward metrics "as verbatim" as possible (adding the necessary labels for indicating the origin is the major exception for that - but that's already in the nature of aggregating).

**Comment by eaglerainbow** [comment]
After some thinking I would like to get that discussed with the folks at prometheus/client_java. That's why I have created the issue linked above.

**Comment by eaglerainbow** [comment]
The discussion at https://github.com/prometheus/client_java/issues/425 ended with the insight that an a missing `# HELP` line is equivalent to a `# HELP` line with an empty docString. 

I have implemented a corresponding conversion
* for the 0.4.x series with 94656a70d8a5c708ee938eb239d337361fb58f15 and released `0.4.1`. The correction will be included in all later releases of 0.4.x
* for the master codeline (double maintenance) with a585286556d945a7959887d6c675af441d1e956e. The release of `0.5.0-rc3` is still pending, but it will include this fix here, too. All later releases will also include the fix. 

Note that 0.3.x and earlier currently stay uncorrected.
