### ISSUE TITLE
Threads of the Fetcher Pool may get stuck when Reading

### ISSUE THREAD

**Issue by eaglerainbow** [promregator/promregator#94]
## Environment
Promregator 0.5.6
Docker Image

## Summary / Problem Statement
Threads of the MetricsFetcher Pool may get monopolized by hanging read requests, which do not time out properly. Thus, there is resource leakage, which eventually may cause thread resource starvation. Polling then is no longer possible.

## Observed Behavior
``` 
"pool-1-thread-9" #79 prio=5 os_prio=0 tid=0x00007fb98c047800 nid=0x57 runnable [0x00007fb987201000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
        at sun.security.ssl.InputRecord.read(InputRecord.java:532)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        - locked <0x00000000f8468500> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        - locked <0x00000000f84680e8> (a sun.security.ssl.AppInputStream)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x00000000f86e3c98> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.Reader.read(Reader.java:140)
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:227)
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:308)
        at org.cloudfoundry.promregator.fetcher.CFMetricsFetcher.call(CFMetricsFetcher.java:129)
        at org.cloudfoundry.promregator.fetcher.CFMetricsFetcher.call(CFMetricsFetcher.java:35)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## Expected Behavior
Threads terminate the attempt to read values after a reasonable timeout.

**Comment by eaglerainbow** [comment]
Problematic line of code: https://github.com/promregator/promregator/blob/61759ebd8ac605ba287d7993532ad35e0475d3dc/src/main/java/org/cloudfoundry/promregator/fetcher/CFMetricsFetcher.java#L117

**Comment by eaglerainbow** [comment]
Worth a read: https://www.baeldung.com/httpclient-timeout

**Comment by eaglerainbow** [comment]
Root cause of the issue was that there wasn't any timeout for connection and socket/read defined. Therefore, the request never returned control back to the thread/thread pool. 
With 0.5.7 (and later versions) there are now the two configuration options

* promregator.scraping.connectionTimeout
* promregator.scraping.socketReadTimeout

available (and configured with default values of 5 seconds) to prevent the same from happening.

**Comment by eaglerainbow** [comment]
0.5.7 is released.
